const DATA_URL="data/Monitoring-AHI.csv";
let raw=[],filtered=[],page=1,pageSize=10;
const TYPES=["Power Transformer","Current Transformer","Potential Transformer","Circuit Breaker","Disconnecting Switch","Lightning Arrester","Neutral Grounding Resistance","Reactor","Capacitor"];
const AHI=[["1 - Very Good","c1"],["2 - Good","c2"],["3 - Fair","c3"],["4 - Poor","c4"],["5 - Critical","c5"]];
const AGE_RULES={"Power Transformer":[19,30],"Reactor":[19,30],"Neutral Grounding Resistance":[19,30],"Current Transformer":[14,25],"Potential Transformer":[14,25],"Capacitor":[14,25],"Circuit Breaker":[14,20],"Disconnecting Switch":[14,20],"Lightning Arrester":[9,15]};
const cols=["Unit Induk","Unit Pelaksana","Ultg","Gardu Induk","Bay","Penempatan","Phasa","Techidentno","Jenis Aset","Merk","Serial ID","Status Asset","Tipe Aset","Tegangan","Tahun Buat","Usia Aset","Kategori Umur","AHI","Parameter Pemicu"];
const $=id=>document.getElementById(id);
function parseCSV(t){let rows=[],row=[],cell="",q=false;for(let i=0;i<t.length;i++){let c=t[i];if(c=='"'){if(q&&t[i+1]=='"'){cell+='"';i++}else q=!q}else if(c==";"&&!q){row.push(cell);cell=""}else if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&t[i+1]=="\n")i++;row.push(cell);if(row.some(x=>x.trim()!=""))rows.push(row);row=[];cell=""}else cell+=c}if(cell!=""||row.length){row.push(cell);rows.push(row)}let h=rows.shift().map(x=>x.replace(/^\uFEFF/,"").trim());return rows.map(a=>Object.fromEntries(h.map((k,i)=>[k,(a[i]??"").trim()])));}
function num(v){let m=String(v||"").replace(",",".").match(/-?\d+(\.\d+)?/);return m?Number(m[0]):null}
function voltageGroup(v){let n=num(v);return n!==null&&n<30?"incoming":n!==null&&n>=70&&n<=500?"70-500":"other"}
function age(r){let y=num(r["Tahun Buat"]);return y?new Date().getFullYear()-y:null}
function ageCat(r){let a=age(r),rule=AGE_RULES[r["Jenis Aset"]];if(a===null||!rule)return"—";return a<=rule[0]?"Muda":a<=rule[1]?"Tua":"Sangat Tua"}
function fmt(n){return Number(n||0).toLocaleString("id-ID")}
function pct(n,d){return d?((n/d)*100).toFixed(1).replace(".",",")+"%":"0,0%"}
function fill(id,values){let s=$(id);s.innerHTML='<option value="">Semua</option>'+values.map(v=>`<option>${v}</option>`).join("")}
function unique(f){return [...new Set(raw.map(r=>r[f]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"id"))}
function populate(){fill("unitInduk",unique("Unit Induk"));fill("upt",unique("Unit Pelaksana"));fill("ultg",unique("Ultg"));fill("gi",unique("Gardu Induk"));fill("bay",unique("Bay"));fill("phasa",unique("Phasa"));fill("jenis",TYPES);fill("ahi",AHI.map(x=>x[0]))}
function apply(){let vg=$("voltageGroup").value,v={unitInduk:$("unitInduk").value,upt:$("upt").value,ultg:$("ultg").value,gi:$("gi").value,bay:$("bay").value,phasa:$("phasa").value,jenis:$("jenis").value,ahi:$("ahi").value};filtered=raw.filter(r=>voltageGroup(r.Tegangan)===vg&&(!v.unitInduk||r["Unit Induk"]===v.unitInduk)&&(!v.upt||r["Unit Pelaksana"]===v.upt)&&(!v.ultg||r.Ultg===v.ultg)&&(!v.gi||r["Gardu Induk"]===v.gi)&&(!v.bay||r.Bay===v.bay)&&(!v.phasa||r.Phasa===v.phasa)&&(!v.jenis||r["Jenis Aset"]===v.jenis)&&(!v.ahi||r.AHI===v.ahi));page=1;render()}
function render(){kpis();ahiDonut();assetAhi();ageDonut();ageBars();table()}
function kpis(){let valid=filtered.filter(r=>/^([1-5]) - /.test(r.AHI)),total=valid.length,counts=AHI.map(([n])=>valid.filter(r=>r.AHI===n).length),arr=[["TOTAL ASET",total,"100%","total"],...AHI.map((a,i)=>[a[0],counts[i],pct(counts[i],total),["good","good2","fair","poor","critical"][i]])];$("kpis").innerHTML=arr.map(x=>`<div class="kpi ${x[3]}"><div class="label">${x[0]}</div><div class="num">${fmt(x[1])}</div><div class="pct">${x[2]}</div></div>`).join("")}
function donut(id,items,total){let colors=["#20a46b","#f2b400","#f07800","#e53935","#111"],sum=items.reduce((a,x)=>a+x.v,0)||1,acc=0;let bg=items.map((x,i)=>{let s=acc/sum*360;acc+=x.v;return `${colors[i]} ${s}deg ${acc/sum*360}deg`}).join(",");$(id).innerHTML=`<div><div class="donut" style="background:conic-gradient(${bg})"><div class="donut-inner">${fmt(total)}<small>Total</small></div></div><div class="legend">${items.map((x,i)=>`<div><i class="dot" style="background:${colors[i]}"></i>${x.n} &nbsp; ${fmt(x.v)} (${pct(x.v,total)})</div>`).join("")}</div></div>`}
function ahiDonut(){donut("ahiDonut",AHI.map(([n])=>({n,v:filtered.filter(r=>r.AHI===n).length})),filtered.filter(r=>/^([1-5]) - /.test(r.AHI)).length)}
function assetAhi(){let rows=TYPES.map(t=>{let a=filtered.filter(r=>r["Jenis Aset"]===t),v=a.filter(r=>/^([1-5]) - /.test(r.AHI)),cells=AHI.map(([n])=>{let x=v.filter(r=>r.AHI===n).length;return`<td><b>${fmt(x)}</b><br>${pct(x,v.length)}</td>`}).join("");return`<tr><td>${t}</td><td>${fmt(a.length)}</td>${cells}</tr>`}).join("");$("assetAhiTable").innerHTML=`<table><thead><tr><th>Jenis Peralatan</th><th>Total</th>${AHI.map(([n])=>`<th>${n}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>`}
function ageDonut(){let a=["Muda","Tua","Sangat Tua"].map(n=>({n,v:filtered.filter(r=>ageCat(r)===n).length}));donut("ageDonut",a,a.reduce((s,x)=>s+x.v,0))}
function ageBars(){$("ageBars").innerHTML=TYPES.map(t=>{let a=filtered.filter(r=>r["Jenis Aset"]===t),n=a.length||1,v=["Muda","Tua","Sangat Tua"].map(c=>a.filter(r=>ageCat(r)===c).length);return`<div class="age-row"><span>${t}</span><div class="bar"><i class="muda" style="width:${v[0]/n*100}%">${pct(v[0],a.length)}</i><i class="tua" style="width:${v[1]/n*100}%">${pct(v[1],a.length)}</i><i class="sangat" style="width:${v[2]/n*100}%">${pct(v[2],a.length)}</i></div></div>`}).join("")}
function table(){let q=$("search").value.toLowerCase(),rows=filtered.filter(r=>cols.some(c=>String(c==="Usia Aset"?age(r):c==="Kategori Umur"?ageCat(r):r[c]||"").toLowerCase().includes(q))),pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages)page=pages;let view=rows.slice((page-1)*pageSize,page*pageSize);$("assetTable").querySelector("thead").innerHTML="<tr>"+cols.map(c=>`<th>${c}</th>`).join("")+"</tr>";$("assetTable").querySelector("tbody").innerHTML=view.map(r=>"<tr>"+cols.map(c=>{let v=c==="Usia Aset"?age(r):c==="Kategori Umur"?ageCat(r):r[c]||"—";if(c==="AHI"){let k=String(v).charAt(0);return`<td><span class="ahi-badge ${({"1":"c1","2":"c2","3":"c3","4":"c4","5":"c5"})[k]||""}>${v}</span></td>`}return`<td>${v}</td>`}).join("")+"</tr>").join("");$("resultCount").textContent=`Menampilkan ${fmt(Math.min(rows.length,(page-1)*pageSize+1))}–${fmt(Math.min(rows.length,page*pageSize))} dari ${fmt(rows.length)} data`;$("pageInfo").textContent=`Halaman ${page} / ${pages}`}
function githubRepo(){let h=location.hostname,p=location.pathname.split("/").filter(Boolean);if(!h.endsWith(".github.io"))return null;let owner=h.split(".")[0],repo=p[0]||`${owner}.github.io`;return{owner,repo}}
async function updateDate(){let repo=githubRepo();if(!repo)return;try{let u=`https://api.github.com/repos/${repo.owner}/${repo.repo}/commits?path=data/Monitoring-AHI.csv&per_page=1`;let r=await fetch(u,{headers:{Accept:"application/vnd.github+json"},cache:"no-store"});if(!r.ok)throw Error();let j=await r.json(),d=j[0]?.commit?.committer?.date;if(d){let s=new Date(d).toLocaleDateString("id-ID",{day:"2-digit",month:"long",year:"numeric"});$("lastDate").textContent=s;$("sideDate").textContent=s}}catch(e){$("lastDate").textContent="Tidak tersedia";$("sideDate").textContent="Tidak tersedia"}}
$("applyBtn").onclick=apply;$("resetBtn").onclick=()=>{document.querySelectorAll("select").forEach(s=>s.value="");$("voltageGroup").value="70-500";apply()};$("voltageGroup").onchange=apply;$("search").oninput=()=>{page=1;table()};$("pageSize").onchange=e=>{pageSize=+e.target.value;page=1;table()};$("prev").onclick=()=>{if(page>1){page--;table()}};$("next").onclick=()=>{let n=filtered.length;if(page<Math.ceil(n/pageSize)){page++;table()}};$("exportBtn").onclick=()=>{let out=cols.join(";")+"\n"+filtered.map(r=>cols.map(c=>c==="Usia Aset"?age(r):c==="Kategori Umur"?ageCat(r):r[c]||"").map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+out],{type:"text/csv"}));a.download="AHI_Power_Inspect_Filtered.csv";a.click()};
Promise.all([fetch(DATA_URL+"?v="+Date.now(),{cache:"no-store"}).then(r=>r.text()),updateDate()]).then(([t])=>{raw=parseCSV(t);populate();apply()}).catch(()=>{document.body.innerHTML="<div style='padding:40px;font-family:Arial'><h2>CSV belum terbaca</h2><p>Pastikan file <b>data/Monitoring-AHI.csv</b> ada di repository.</p></div>"});
